server:
  port: 8099
management:
  endpoint:
    health:
      enabled: true
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    platform: postgresql
  flyway:
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
youtube:
  v3:
    api:
      key: ${YOUTUBE_API_KEY}
      urls:
        channel: https://www.googleapis.com/youtube/v3/channels?key={key}&id={channelId}&part=snippet&maxResults=1
        videos: https://www.googleapis.com/youtube/v3/search?key={key}&channelId={channelId}&part=snippet&type=video&maxResults=50&pageToken={pageToken}
database:
  manager:
    delay: 10000
