server:
  port: 8099
management:
  endpoint:
    health:
      enabled: true
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_YA_URL:jdbc:postgresql://${DB_YA_HOST:localhost}:${DB_YA_PORT:5432}/${DB_YA_DATABASE:postgres}?currentSchema=${DB_YA_SCHEMA:youtube_analytic}}
    username: ${DB_YA_USERNAME:postgres}
    password: ${DB_YA_PASSWORD:admin}
  flyway:
    url: ${DB_YA_URL:jdbc:postgresql://${DB_YA_HOST:localhost}:${DB_YA_PORT:5432}/${DB_YA_DATABASE:postgres}}
    user: ${DB_YA_USERNAME:postgres}
    password: ${DB_YA_PASSWORD:admin}
    baselineOnMigrate: true
    schemas: [ '${DB_YA_SCHEMA:youtube_analytic}' ]
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: dev
springdoc:
  api-docs:
    path: youtube/analitic/documentation
  swagger-ui:
    path: youtube/analitic/documentation.html
youtube:
  v3:
    api:
      key: ${YOUTUBE_API_KEY}
      urls:
        channel: https://www.googleapis.com/youtube/v3/channels?key={key}&id={channelId}&part=snippet&maxResults=1
        videos: https://www.googleapis.com/youtube/v3/search?key={key}&channelId={channelId}&part=snippet&type=video&maxResults=500&pageToken={pageToken}
  analytic:
    collector:
      cron: 0 0 * * * *
      enabled: true
    security:
      jwt:
        key: ${YOUTUBE_SECURITY_SECRET_KEY}
        expiration: 300000
